This commit was manufactured by cvs2svn to create branch 'r3_80_mcote'.
git-svn-id: file:///home/apenwarr/alumnit-svn/public/branches/r3_80_mcote@5624 6619c942-59fa-0310-bf43-a07aaa81d9ac

diff --git a/wvtesthelper b/wvtesthelper
--- a/wvtesthelper
+++ b/wvtesthelper
@@ -6,9 +6,21 @@
 #
 export WVTESTRUN="env"
 
+reportcode()
+{
+    CODE=$1
+    if [ "$CODE" = "0" ]; then
+        echo "! wvtesthelper   Test program exited ok    ok"
+    else
+        echo "! wvtesthelper   Test program aborted (code $CODE)   FAILED"
+    fi
+    return $CODE
+}
+
 if [ -z "$DISPLAY" ]; then
     exec "$@"
 else
-    ( "$@" ) | ($WVSTREAMS/wvtestmeter || cat)
+    ( "$@"; reportcode $?) \
+    	| ($WVSTREAMS/wvtestmeter || cat)
     exit ${PIPESTATUS[0]}
 fi
